// src/ui/svelte/GeneratedUi.svelte
<script lang="ts">
  import type { Attachment } from "svelte/attachments";
  import type {
    GeneratedUiActionEndEvent,
    GeneratedUiActionEvent,
    GeneratedUiRenderer,
    GeneratedUiRenderSession,
  } from "../renderer.ts";
  import type {
    GeneratedUi as GeneratedUiController,
    GeneratedUiFrame,
  } from "../index.ts";

  type Props = {
    readonly ui: GeneratedUiController;
    readonly renderer: GeneratedUiRenderer<HTMLDivElement>;
    readonly class?: string;
    readonly onError?: (error: unknown) => void;
    readonly onRender?: (frame: GeneratedUiFrame) => void;
    readonly onActionStart?: (event: GeneratedUiActionEvent) => void;
    readonly onActionEnd?: (event: GeneratedUiActionEndEvent) => void;
  };

  let {
    ui,
    renderer,
    class: className = "",
    onError,
    onRender,
    onActionStart,
    onActionEnd,
  }: Props = $props();

  let running = $state(false);
  let surfaceError = $state("");
  let mounted: GeneratedUiRenderSession | undefined;
  let mountedUi: GeneratedUiController | undefined;

  const attachGeneratedUi: Attachment<HTMLDivElement> = (node) => {
    mountedUi = ui;
    mounted = renderer.mount(node, ui, {
      onError(error) {
        surfaceError = errorText(error);
        onError?.(error);
      },
      onRender(frame) {
        surfaceError = "";
        onRender?.(frame);
      },
      onActionStart(event) {
        running = true;
        onActionStart?.(event);
      },
      onActionEnd(event) {
        running = false;
        onActionEnd?.(event);
      },
    });

    return () => {
      mounted?.destroy();
      mounted = undefined;
      mountedUi = undefined;
    };
  };

  $effect(() => {
    if (!mounted || mountedUi === ui) return;

    mountedUi = ui;
    mounted.update(ui);
  });

  function errorText(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
  }
</script>

<div class={`generated-ui-shell ${className}`.trim()}>
  <div {@attach attachGeneratedUi} class="generated-ui"></div>
  {#if running}
    <p class="generated-ui-status">Running generated action...</p>
  {/if}
  {#if surfaceError}
    <p class="generated-ui-error">{surfaceError}</p>
  {/if}
</div>

// src/ui/solid/GeneratedUi.tsx
import { createEffect, createSignal, onCleanup, onMount } from "solid-js";
import type { JSX } from "solid-js";
import type {
  GeneratedUiActionEndEvent,
  GeneratedUiActionEvent,
  GeneratedUiRenderer,
  GeneratedUiRenderSession,
} from "../../renderer.ts";
import type {
  GeneratedUi as GeneratedUiController,
  GeneratedUiFrame,
} from "../index.ts";

export interface GeneratedUiProps {
  readonly ui: GeneratedUiController;
  readonly renderer: GeneratedUiRenderer<HTMLDivElement>;
  readonly class?: string;
  readonly className?: string;
  readonly onError?: (error: unknown) => void;
  readonly onRender?: (frame: GeneratedUiFrame) => void;
  readonly onActionStart?: (event: GeneratedUiActionEvent) => void;
  readonly onActionEnd?: (event: GeneratedUiActionEndEvent) => void;
}

export function GeneratedUi(props: GeneratedUiProps): JSX.Element {
  let root: HTMLDivElement | undefined;
  let mounted: GeneratedUiRenderSession | undefined;
  let mountedUi: GeneratedUiController | undefined;
  const [running, setRunning] = createSignal(false);
  const [surfaceError, setSurfaceError] = createSignal("");

  onMount(() => {
    if (!root) return;

    mountedUi = props.ui;
    mounted = props.renderer.mount(root, props.ui, {
      onError(error) {
        setSurfaceError(errorText(error));
        props.onError?.(error);
      },
      onRender(frame) {
        setSurfaceError("");
        props.onRender?.(frame);
      },
      onActionStart(event) {
        setRunning(true);
        props.onActionStart?.(event);
      },
      onActionEnd(event) {
        setRunning(false);
        props.onActionEnd?.(event);
      },
    });
  });

  createEffect(() => {
    const nextUi = props.ui;
    if (!mounted || mountedUi === nextUi) return;

    mountedUi = nextUi;
    mounted.update(nextUi);
  });

  onCleanup(() => {
    mounted?.destroy();
    mounted = undefined;
    mountedUi = undefined;
  });

  return (
    <div
      class={joinClasses("generated-ui-shell", props.class, props.className)}
    >
      <div
        ref={(element) => {
          root = element;
        }}
        class="generated-ui"
      />
      {running() ? (
        <p class="generated-ui-status">Running generated action...</p>
      ) : null}
      {surfaceError() ? (
        <p class="generated-ui-error">{surfaceError()}</p>
      ) : null}
    </div>
  );
}

export default GeneratedUi;

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function joinClasses(...classes: readonly (string | undefined)[]): string {
  return classes.filter(Boolean).join(" ");
}
